### ISSUE TITLE
Refactor Subscribers API to conform to new design

### ISSUE THREAD

**Issue by mayorJAY** [novuhq/novu-java#55]
We want to refactor the Subscribers API to address compatibility issues with Micronaut and Quarkus arising from the library's reliance on Spring framework.

We would like to have the Events API migrated to the new REST dependency and ensure the on going updates to the unit tests to validate the modifications and uphold code quality.

For guidance on the expected changes, kindly refer to this pull request #54.

PLEASE BRANCH OFF `STAGING` BRANCH AND ALL PRS SHOULD GO TO `STAGING` BRANCH FOR THESE CHANGES

**Comment by debanjanc01** [comment]
@mayorJAY could you assign this to me?

**Comment by debanjanc01** [comment]
hey @mayorJAY , the staging branch seems to have code issues.
The [Novu.java](https://github.com/novuhq/novu-java/blob/acd4cd829e5b51e0a77c2106f29778940faa5379/src/main/java/co/novu/common/base/Novu.java#L162) class 
seems to have compilation errors because of `new FeedsHandler(restHandler, novuConfig);` and `new MessageHandler(restHandler, novuConfig);`. These constructors are missing in the class.

**Comment by mayorJAY** [comment]
It should be fine now

**Comment by mayorJAY** [comment]
@debanjanc01 there seems to be no traction on this issue. Are you still working on it?

**Comment by debanjanc01** [comment]
Hey @mayorJAY , yes I'm working on it. :) 
Couldn't build the branch because of the compilation failures.

**Comment by debanjanc01** [comment]
Hey @mayorJAY , I've raised the PR for the same.
