### ISSUE TITLE
Outdated usage documentation for version `v1.4.0`

### ISSUE THREAD

**Issue by shygnome** [novuhq/novu-java#96]
It seems the examples in the usage documentation are different from the actual SDK in version `v1.4.0`. Any plan to update the documentation?

**Comment by m-a-r-1912** [comment]
Hi @shygnome, you're talking about the Usage section in this repo's README not the documentation hosted on novu.co, right?

**Comment by shygnome** [comment]
> Hi @shygnome, you're talking about the Usage section in this repo's README not the documentation hosted on novu.co, right?

I think both this repo's README and the one hosted in docs.novu.co are same. Like in this API reference page https://docs.novu.co/api-reference/events/trigger-event. The java example one still using `HashMap` object. We are supposed to use the `TriggerEventRequest` and other request class, right? @m-a-r-1912

**Comment by m-a-r-1912** [comment]
Yeah, according to this repo, the `triggerEvent` method accepts a `TriggerEventRequest` as parameter. So any documentation using `HashMap` type as parameter is wrong. We might need to create a issue(s) for the Docs repo as well. Since that's the code responsible for the api-reference pages. 

FYI, it appears that one of the documentation pages has a few up to date examples [https://docs.novu.co/quickstarts/java](https://docs.novu.co/quickstarts/java). Potentially some of the examples from there could simply be copied over to the out of date docs.

**Comment by mayorJAY** [comment]
Closing this as resolved
